name: build-macos13-arm64
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    env:
      LDFLAGS: -L/usr/local/opt/bison/lib
    steps:
      - uses: actions/checkout@v4
      - name: xcode switch
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      - name: Install homebrew
        run: brew install autoconf automake libtool cmake bison curl
      - name: set up path
        run: echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
      - name: Test path
        run: echo "$PATH"
      - name: Test LDFLAGS
        run: echo "$LDFLAGS"
      - name: Test LDFLAGS
        run: echo $LDFLAGS
      - name: check bison version
        run: bison --version
      - name: create pickup directory
        run: mkdir pickup
      - name: git clone
        run: git clone -b standalone https://github.com/vpinball/vpinball
      - name: zip source directory
        run: zip pickup/vpinball-source.zip vpinball
      - name: validate pickup and zip
        working-directory: pickup
        run: ls -la
      - name: check base directory
        run: pwd
      - name: list base directory
        run: ls -la
      - name: run external.sh
        working-directory: vpinball/standalone/macos-arm64
        run: ./external.sh
      - name: copy CMakeLists
        working-directory: vpinball
        run: cp standalone/cmake/CMakeLists_gl-macos-arm64.txt CMakeLists.txt
      - name: cmake build
        working-directory: vpinball
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: build
        working-directory: vpinball
        run: cmake --build build -- -j$(sysctl -n hw.ncpu)
      - name: look at what's there in vpinball
        working-directory: vpinball
        run:  ls -la
      - name: look at what's there in main directory
        run:  ls -la
      - name: look at what's there in build directory
        working-directory: vpinball/build
        run:  ls -la
      - name: compress the app
        working-directory: vpinball/build
        run: zip ../../pickup/VPX_os13_arm64.zip VPinballX_GL.app
      - name: download the app
        uses: actions/upload-artifact@v4
        with:
          name: VPX_os13_arm64.zip
          path: pickup
      - name: download the source
        uses: actions/upload-artifact@v4
        with:
          name: vpinball-source.zip
          path: pickup