name: vpx-build-macos12
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - name: xcode switch
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      - name: Install homebrew
        run: brew install autoconf automake libtool cmake bison curl
      - name: set up path
        run: export PATH="$(brew --prefix bison)/bin:$PATH"
      - name: Test path
        run: which bison
      - name: check bison version
        run: bison --version
      - name: git clone
        run: git clone -b standalone https://github.com/vpinball/vpinball
      - name: cd to platform architecture directory
        run: cd vpinball/standalone/macos-arm64
      - name: run external.sh
        run: ./external.sh
      - name: cd to build directory
        run: cd ../..
      - name: copy CMakeLists
        run: cp standalone/cmake/CMakeLists_gl-macos-arm64.txt CMakeLists.txt
      - name: cmake build
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: build
        run: cmake --build build -- -j$(sysctl -n hw.ncpu)

