name: vpx-build-macos12
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: xcode switch
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      - name: Install homebrew
        run: brew install autoconf automake libtool cmake bison curl
      - name: set up path
        run: echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
      - name: Test path
        env:
          MY_PATH: ${{ env.PATH }}
        run: echo "$MY_PATH"
      - name: set up LDFLAGS in github env
        run: echo "-L/usr/local/opt/bison/lib" >> $GITHUB_ENV
      - name: Test LDFLAGS
        env:
          LDFLAGS: ${{ env.LDFLAGS }}
        run: echo "$LDFLAGS"
      - name: Test LDFLAGS
        run: echo $LDFLAGS
      - name: check bison version
        run: bison --version
      - name: git clone
        run: git clone -b standalone https://github.com/vpinball/vpinball
      - name: cd to platform architecture directory
        run: cd vpinball/standalone/macos-arm64
      - name: get current directory
        run: pwd
      - name: check path
        run: echo $PATH
      - name: run external.sh
        run: ./external.sh
      - name: cd to build directory
        run: cd ../..
      - name: copy CMakeLists
        run: cp standalone/cmake/CMakeLists_gl-macos-arm64.txt CMakeLists.txt
      - name: cmake build
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: build
        run: cmake --build build -- -j$(sysctl -n hw.ncpu)
      - name: compress the app
        run: tar -czvf VPinballX_GL.app.tar.gz build/arm/VPinballX_GL.app 
      - name: download the artifact
        uses: actions/upload-artifact@v2
        with:
          -name: VPinballX_GL.app.tar.gz
          path: ./
        